from __future__ import annotations

from typing import Protocol

from harness_context.api.v2 import ContextPackageV2, PrepareContextRequest


class RefreshCommands(Protocol):
    def execute(self, workspace_id: str, paths: list[str] | None = None) -> dict: ...
    def invalidate(self, workspace_id: str, target: str) -> dict: ...


class ContextQueries(Protocol):
    def prepare(self, request: PrepareContextRequest) -> ContextPackageV2: ...
    def prepare_values(self, **values) -> dict: ...


class WorkspaceCommands(Protocol):
    def register(self, workspace_id: str, roots: list[str], initial_refresh: bool = False) -> dict: ...


class RetrievalQueries(Protocol):
    def plan(self, workspace_id: str, query: str, available_input_tokens: int, strategy_override: str = "") -> dict: ...
    def retrieve(self, workspace_id: str, query: str, top_k: int = 12, graph_expand: bool = True, token_budget: int = 4_000) -> dict: ...
    def stats(self, workspace_id: str) -> dict: ...
    def snapshot_is_current(self, workspace_id: str) -> bool: ...


class MemoryCommandsQueries(Protocol):
    def save(self, workspace_id: str, key: str, value: str, **options) -> dict: ...
    def search(self, workspace_id: str, query: str, **options) -> list[dict]: ...
    def delete(self, workspace_id: str, key: str, mtype: str = "semantic") -> dict: ...
    def list(self, workspace_id: str, mtype: str = "", limit: int = 30) -> list[str]: ...


class HandoffCommandsQueries(Protocol):
    def prepare(self, workspace_id: str, messages_json: str, **options) -> dict: ...
    def restore(self, workspace_id: str, handoff_id: str) -> dict: ...
    def list(self, workspace_id: str, limit: int = 30) -> list[dict]: ...
    def delete(self, workspace_id: str, handoff_id: str) -> dict: ...
    def purge(self) -> dict: ...


class EccQueries(Protocol):
    def status(self) -> dict: ...
    def search(self, query: str, limit: int = 4) -> dict: ...

class SkillCommandsQueries(Protocol):
    def route(self, workspace_id: str, task: str, **options) -> dict: ...
    def feedback(self, workspace_id: str, route_id: str, outcome: str, **options) -> dict: ...
    def learning_status(self, workspace_id: str, limit: int = 20) -> dict: ...
