"""Public CTXORA product metadata."""

BRAND_NAME = "CTXORA"
PRODUCT_NAME = "CTXORA Engine"
MCP_SERVER_NAME = "CTXORA MCP"
CLI_NAME = "ctxora"
MCP_CLI_NAME = "ctxora-mcp"
DISTRIBUTION_NAME = "ctxora-engine"
MCP_SERVER_KEY = "ctxora"
FREE_PLAN_NAME = "CTXORA Free"
PAID_PLAN_NAME = "CTXORA Pro"
PAID_PLAN_STATUS = "waitlist"
TAGLINE = "Index once. Ground every agent."
DESCRIPTION = "Local-first context engine for coding agents."
WORKSPACE_DIR_NAME = ".ctxora"
LEGACY_WORKSPACE_DIR_NAME = ".harness"
